import { route } from '@/common/api';
import ErrorBoundary from '@/components/error/ErrorBoundary';
import { Providers } from '@/components/providers';
import { connect } from '@/database/mongoConfig';
import '@/styles/globals.css';
import Link from 'next/link';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Irisations ADM',
  description: 'Generated by Next.js'
};

export default function IrisationAdminLayout({
  children
}: {
  children: React.ReactNode;
}) {
  connect();
  return (
    <html lang='en'>
      <body>
        <ErrorBoundary>
          <Providers>

            <Toaster
              position='bottom-right' // Position des toasts
              reverseOrder={false} // Ordre de défilement
            />
            {children}
            <footer style={{ backgroundColor: 'ghostwhite' }}>
              footer Irisation Adm
            </footer>
          </Providers>
        </ErrorBoundary>
      </body>
    </html>
  );
}
